name: Scrape Books

on:
  workflow_dispatch: # Run manually or schedule this job

jobs:
  scrape-books:
    runs-on: ubuntu-latest
    timeout-minutes: 310 # Max duration for the job is 5 hours and 10 minutes

    strategy:
      fail-fast: false
      max-attempts: 3 # Retry the job up to 3 times if it fails

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: bundle install

      - name: Run the scraper
        run: ruby scrape_books.rb

      - name: Upload final artifacts
        uses: actions/upload-artifact@v3
        with:
          name: scraped-books-artifacts
          path: artifacts.tar.gz
