name: Scrape Books

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true

    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install
      env:
        BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile

    - name: Start Scraper
      run: |
        for ((i=0; i<20; i++)); do  # 20 iterations (5 hours total, 15 minutes per iteration)
          timestamp=$(date +"%Y%m%d_%H%M%S")
          json_file="books_${timestamp}.json"
          ruby scrape_books.rb --output $json_file
          if [ -f "$json_file" ]; then
            echo "JSON file $json_file created. Uploading..."
            gh run upload-artifact --name "books_${timestamp}" --path "$json_file"
          fi
          sleep 900 # Wait 15 minutes (900 seconds) before the next iteration
        done
      env:
        BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile
        RUBYLIB: ${{ github.workspace }}/vendor/bundle/ruby/3.1.0
