name: Scraping Books

on:
  push:
    branches:
      - eachloop  # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - eachloop  # Trigger on pull request to the 'main' branch

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        batch: 
          - { start: 0, end: 100 }
          - { start: 101, end: 200 }
          - { start: 201, end: 300 }
          - { start: 301, end: 400 }
          - { start: 401, end: 400 }
          - { start: 401, end: 500 }
          - { start: 501, end: 600 }
          - { start: 601, end: 700 }
          - { start: 701, end: 800 }
          - { start: 801, end: 900 }
          - { start: 901, end: 900 }
          - { start: 901, end: 1000 }
          - { start: 1001, end: 1100 }
          - { start: 1101, end: 1200 }
          - { start: 1201, end: 1300 }
          - { start: 1301, end: 1400 }
          - { start: 1401, end: 1500 }
          - { start: 1501, end: 1600 }
          - { start: 1601, end: 1700 }
          - { start: 1701, end: 1800 }
          - { start: 1801, end: 1900 }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install dependencies
        run: bundle install

      - name: Run scraper
        run: |
          ruby scraping.rb ${{ matrix.batch.start }} ${{ matrix.batch.end }}
