name: Scrape Books


on:
  push:
    branches:
      - poesy  # Trigger on push to the 'eachloop' branch
  pull_request:
    branches:
      - poesy  # Trigger on pull request to the 'eachloop' branch

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        batch: 
          - { start: 0, end: 50 }
          - { start: 51, end: 100 }
          - { start: 101, end: 150 }
          - { start: 151, end: 200 }
          - { start: 201, end: 250 }
          - { start: 251, end: 300 }
          - { start: 301, end: 350 }
          - { start: 351, end: 400 }
          - { start: 401, end: 450 }
          - { start: 451, end: 500 }
          - { start: 501, end: 550 }
          - { start: 551, end: 610 }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install dependencies
        run: bundle install

      - name: Run scraper and create JSON artifact
        run: |
          ruby poesy.rb ${{ matrix.batch.start }} ${{ matrix.batch.end }} > ${{ matrix.batch.start }}-${{ matrix.batch.end }}.json

      - name: Upload JSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: batch-${{ matrix.batch.start }}-${{ matrix.batch.end }}
          path: ${{ matrix.batch.start }}-${{ matrix.batch.end }}.json
  
