name: Scrape Books

on:
  workflow_dispatch:  # Allows manual trigger
  
jobs:
  scrape_part1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: bundle install
        
      - name: Run scraper for first batch
        run: ruby scraper_books.rb links.txt
        
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: results-links1
          path: books.json

  scrape_part2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: bundle install
        
      - name: Run scraper for second batch
        run: ruby scraper_books.rb links1.txt
        
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: results-links2
          path: books1.json

  scrape_part3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: bundle install
        
      - name: Run scraper for third batch
        run: ruby scrape_books.rb links2.txt
        
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: results-links3
          path: books2.json
