name: Scraping Books

on:
  push:
    branches:
      - eachloop  # Trigger on push to the 'eachloop' branch
  pull_request:
    branches:
      - eachloop  # Trigger on pull request to the 'eachloop' branch

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        batch: 
          - { start: 20, end: 22 }
          - { start: 70, end: 72 }
          
         

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install dependencies
        run: bundle install

      - name: Run scraper and create JSON artifact
        run: |
          ruby scraping.rb ${{ matrix.batch.start }} ${{ matrix.batch.end }} > ${{ matrix.batch.start }}-${{ matrix.batch.end }}.json

      - name: Upload JSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: batch-${{ matrix.batch.start }}-${{ matrix.batch.end }}
          path: ${{ matrix.batch.start }}-${{ matrix.batch.end }}.json
