name: Scrape Books

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true

    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install

    - name: Start Scraper
      run: |
        # Run the scraper script and generate the JSON file
        timestamp=$(date +"%Y%m%d_%H%M%S")
        json_file="books_${timestamp}.json"
        bundle exec ruby scrape_books.rb --output $json_file  # Run with bundle exec
        
        # If the JSON file is generated, upload it
        if [ -f "$json_file" ]; then
          echo "JSON file $json_file created. Uploading..."
          gh run upload-artifact --name "books_${timestamp}" --path "$json_file"
        fi
