name: Scrape Books

on:
  push:
    branches:
      - test  # Runs ONLY on the 'test' branch

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      matrix:
        range: 
          - { start: 1, end: 100 }
          - { start: 101, end: 200 }
          - { start: 201, end: 300 }
          - { start: 301, end: 400 }
          - { start: 401, end: 500 }
          - { start: 501, end: 600 }
          - { start: 601, end: 700 }
          - { start: 701, end: 800 }
          - { start: 801, end: 900 }
          - { start: 901, end: 1000 }
          - { start: 1001, end: 1100 }
          - { start: 1101, end: 1200 }
          - { start: 1201, end: 1300 }
          - { start: 1301, end: 1400 }
          - { start: 1401, end: 1500 }
          - { start: 1501, end: 1600 }
          - { start: 1601, end: 1700 }
          - { start: 1701, end: 1800 }
          - { start: 1801, end: 1900 }
          - { start: 1901, end: 2000 }
          - { start: 2001, end: 2100 }
          - { start: 2101, end: 2200 }
          - { start: 2201, end: 2300 }
          - { start: 2301, end: 2400 }
          - { start: 2401, end: 2500 }

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install dependencies
        run: |
          gem install capybara selenium-webdriver mechanize json parallel

      - name: Run the scraper
        run: |
          ruby scrape_books.rb "https://www.neelwafurat.com/browse1.aspx?search=books&ddmSubject=10&orderby=rdate&dir=desc&subcat=01" "Islamic Books" ${{ matrix.range.start }} ${{ matrix.range.end }}

      - name: Upload JSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ matrix.range.start }}-${{ matrix.range.end }}
          path: islam3.json

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: csv-${{ matrix.range.start }}-${{ matrix.range.end }}
          path: islam3.csv
