name: Scrape Books

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Specify the Ruby version you need

      - name: Install dependencies
        run: |
          gem install capybara selenium-webdriver mechanize json

      - name: Run the scraper
        run: |
          ruby scrape_books.rb  # Replace with the actual path to your Ruby script

      - name: Upload JSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-json
          path: 7adith.json  # Path to the generated JSON file
