name: Scraping Books

on:
  push:
    branches:
      - eachloop  # Trigger on push to the 'eachloop' branch
  pull_request:
    branches:
      - eachloop  # Trigger on pull request to the 'eachloop' branch

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        batch: 
          - { start: 1901, end: 2000 }
          - { start: 2001, end: 2100 }
          - { start: 2101, end: 2200 }
          - { start: 2201, end: 2300 }
          - { start: 2301, end: 2400 }
          - { start: 2401, end: 2500 }
          - { start: 2501, end: 2545 }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install dependencies
        run: bundle install

      - name: Run scraper and create JSON artifact
        run: |
          ruby scraping.rb ${{ matrix.batch.start }} ${{ matrix.batch.end }} > ${{ matrix.batch.start }}-${{ matrix.batch.end }}.json

      - name: Upload JSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: batch-${{ matrix.batch.start }}-${{ matrix.batch.end }}
          path: ${{ matrix.batch.start }}-${{ matrix.batch.end }}.json
