
name: Scrape Books

on:
  push:
    branches:
      - kareem76-patch-1  # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - kareem76-patch-1  # Trigger on pull request to the 'main' branch

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        part: [links, links1,  links2, links3, links4, links6, links7]  # Runs 9 parallel jobs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Adjust as needed

      - name: Install dependencies
        run: |
          gem install capybara selenium-webdriver mechanize json parallel

      - name: Run the scraper
        run: |
          ruby scraper.rb ${{ matrix.part }}.txt  # Run with correct file

      - name: Upload JSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ matrix.part }}
          path: ${{ matrix.part }}-books.json
