name: Scrape Doha Book Fair

on:
  push:
    branches:
      - booky
  pull_request:
    branches:
      - booky

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Adjust if needed

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y chromium-chromedriver

      - name: Install Ruby gems
        run: |
          gem install bundler
          bundle install || gem install capybara selenium-webdriver json mechanize

      - name: Run the scraper
        env:
          DISPLAY: :99
        run: |
          ruby bookdoha.rb  # or bookdoha.rb

      - name: Upload JSON artifacts
        uses: actions/upload-artifact@v4
        with:
          name: doha-json
          path: '**/*.json'